### ISSUE TITLE
Is there any GCC 7.5 (win32) package  available?

### ISSUE THREAD

**Issue by GrisuBMX** [brechtsanders/winlibs_mingw#10]
Hi,
for a very old project of mine none of the newer GCC versions (from 8.x to 10.x) work.
Can you supply a win32 package of the latest GCC 7.5 branch? I couldn't find it on this site. 
I'm currently using GCC 7.3.0 (i686-win32-dwarf) from: https://sourceforge.net/projects/mingw-w64/files/ and would love to get the latest fixes.

Thanks in advance
Stefan

**Comment by brechtsanders** [comment]
Hi Stefan,
The focus of this project is on recent versions of GCC.
I did however just try my build script on GCC 7.5.0 and it started out badly with:
```
configure: error: Building GCC with plugin support requires a host that supports -fPIC, -shared, -ldl and -rdynamic.
```
I will give it another go with `--disable-plugin` and if it works I will release the build.
If not I'm afraid I won't be putting much time in this.

Also:
Why do you have a need for this old version?
Is a newer version with the right `--std=` compiler option not a more logical solution?
For example `-std=c11` for C and  `-std=c++11` for C++ if you cant the the ISO 2011 C/C++ standard.
You can run this command to see the possible options:
`gcc --help -v 2>/dev/null | grep "  -std="`

Regards
Brecht

**Comment by brechtsanders** [comment]
You're in luck!
I was completely able to build GCC 7.5.0 with only a few tweaks in my build script.
You can download it [here](https://github.com/brechtsanders/winlibs_mingw/releases/tag/7.5.0-7.0.0-r1).
Enjoy.

P.S.: You should probably still stick with a newer version using `-std=` compiler flag as I mentioned earlier.

**Comment by eungenue** [comment]
Hi Brecht,

This might sound unusual, but is there any chance you build fresh gcc for Windows XP SP3 32 bit?
I checked recent 32 bit builds and they are not working on Windows XP.  I took the build you mentioned above and it works, but I'm curious if it is still possible to get some fresh gcc "with a few tweaks"?

**Comment by brechtsanders** [comment]
I doubt it. There are a lot of dependencies that go into MinGW-w64, GCC and binutils, and some of them have come to rely on new features of more recent Windows versions.

Also, Windows versions older than Windows 10 are obsolete and won't be patched. Using a version as old Windows XP is very disturbing if you think about cybersecurity aspects.

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
it is so nice to have gcc 7.5 however it seems that you built it with -g which resulted in everything having some sort of -g information including your configuration and how you built gcc 7.5 itself.
like i could see it was built on drive R:/.

another thing is your gcc version string is too long that it takes ~3KB in every executable built, i just tested this.

while it is really nice to see gcc 7.5 as it is required for older sources to compile properly without generated code side-effects, im not going to use it, sticking to the old mingw.org gcc-6.3

edit:
while i doubt you have time for this, but if possible i would like to learn how to built gcc 7.5 myself, and no i never built gcc and i have no clue about anything needed.

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
closest i could get is gcc-7.3 from here https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/

using win32 threads and dwarf exceptions, their binaries are clean, and binaries produced by their gcc only contain 1 gcc version string, i.e 1 instance, which is only few bytes.

i dont know how to contact these guys behind gcc-7.3, i would like to ask them if they can provide gcc-7.5 or share the steps required to build it.

**Comment by brechtsanders** [comment]
According to https://gcc.gnu.org/develop.html the GCC team is now focusing on GCC 16.
There is no reason for them to still maintain GCC 7 whose last release was 6 years ago.

In I would think there is no reason for you to need GCC 7 either.
Why don't you just use a recent GCC with the `-std=` flag for backwards compatibility as mentioned earlier in this ticket? 
For example `-std=c17` for C or `-std=c++17`.

**Comment by brechtsanders** [comment]
Oh, and about the `-g`, just strip the resulting binaries (`.exe` and `.dll`) with the `strip` command or link then with the `-s` flag to remove the debugging information?

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
> Oh, and about the `-g`, just strip the resulting binaries (`.exe` and `.dll`) with the `strip` command or link then with the `-s` flag to remove the debugging information?

let me try to make it clearer, your gcc-7.5 build was compiled with -g, striping every exe and dll from your distribution is tedious work.
now that is kinda ok.

perhaps this is a bit unclear:
> another thing is your gcc version string is too long that it takes ~3KB in every executable built, i just tested this.

this related to the way you built gcc and crt, a simple hello world program inspection shows this text repeated a lot of times:
"GCC: (MinGW-W64 i686-posix-dwarf, built by Brecht Sanders) 7.5.0"

there should be only 1 gcc version string embedded in whatever executable gcc produces, however in your gcc-7.5, this same text is a lot several times and takes ~2KB. (yes correction here it is 2KB not 3KB)

testing both your version and the version from the link above, your version is 2KB larger.
- your version: 16KB helloworld
- from link above: 14KB helloworld

there is huge different when version string takes 64 bytes vs 2KB.



> In I would think there is no reason for you to need GCC 7 either. Why don't you just use a recent GCC with the `-std=` flag for backwards compatibility as mentioned earlier in this ticket? For example `-std=c17` for C or `-std=c++17`.

it has nothing to do with -std=X (i always use gnu99), gcc's code generation changed significantly in version 8 and above, including default enabled flags and newer flags; binaries produced are different, the layout of code in memory is also different.
while i understand that projects that do self-modifying code or configured to do some assembly level hacks, or depend on certain PE layout should adapt to whatever newer gcc stuff, it doesnt mean that older version should be trashed or not used.

you can ignore the low level stuff they are rare, however gcc < 8 had different inlining rules, this is a bit problematic when compiling some projects; and since function inlinging has nothing to do with C std, gcc is free to do whatever it please as long as the std says something is implementation-defined.
C-std only guarantees your code can be compiled by conforming compiler, writing code that dont rely on behavior outside of the C-std is nearly useless.

and realistically most projects rely on implementation defined, architecture specific and system specific behaviors.
so you got the point, I hope this makes it clear to you why some people still require some specific compiler versions.

note that im not asking you to build gcc 7.5 or fix it or provide people with all gcc version, im simply trying to answer why -std=X is not a thing when seeking older compilers.

also sorry if i said something wrong my language is not english, so dont feel offended.

p.s.  im happy with my old gcc 6.3 and current gcc 7.3 (also i have gcc 4.9.x around just in case for some other stuff)

**Comment by brechtsanders** [comment]
Thanks for clarifying.

It would be interesting to know why the compiler version string ends up in the binaries so many times.

Maybe your build process could play a role in this. Maybe it is in each `.o` file. Maybe it is in each `.a` file one or more times. If it is part of debugging information I would definitely link everything stripped for production releases.

If you have specific issues with newer GCC releases you can always ask at https://gcc.gnu.org/bugzilla/

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
not my build process, it is an issue with how you built gcc and crt.
just so you know what can be found in many files with your gcc-7.5 package, many objects (.o) and archives (.a) contain bunch of unnecessary information including the version string string "GCC: (MinGW-W64 i686-posix-dwarf, built by Brecht Sanders) 7.5.0"
```
-m32 -mtune=generic -march=pentiumpro -g -O2 -std=gnu99
crt/crtexe.c
R:\winlibs32-7.5.0\mingw-w64-v7.0.0\mingw-w64-crt
R:/winlibs32-7.5.0/inst_mingw-w64-7.0.0/share/mingw-w64/include/psdk_inc
```

another example, your gcc.exe has the text "GCC: (MinGW-W64 i686-posix-dwarf, built by Brecht Sanders) 7.5.0" repeated 169 times. (64 byte string * 169 = 10816 which is ~10KB)
the same text gets repeated a lot of times in every executable gcc produces because bunch of object files and static archive are also flooded with this gcc version string which explains why this duplication and increase in size, the more archives and objects you link the more your exe gets larger.

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
```R:\winlibs32-7.5.0\mingw-w64-v7.0.0\mingw-w64-crt```
is the path where you built this gcc package and crt specifically.

i inspected gcc version from sourceforge, it has no information, not even version string in .o or .a, and binaries produced with their gcc.exe will result only in one copy of gcc version string to be included in the final binary.

**Comment by brechtsanders** [comment]
Got it. Sorry for being a bit slow in understanding.

I see what you say is still true for my newer builds too.
Other builds out there are usually cross-compiled (typically from Linux), while I build natively on Windows. And I build every single dependency from source myself.

Maybe that has something to do with it?

I don't see any option in `strip` to get rid of this kind of information though.
Any idea how to prevent the version information to end up in libraries and binaries?

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
the thing that made even start inspecting was mainly the size of the produced exe which a bit bothered me to see an increase when recompiling some of my project.

i never built gcc myself, in fact i dont even know the requirement to build gcc, so i have absolutely no idea.
sorry i cannot help you with this one.

**Comment by brechtsanders** [comment]
I would like to figure this one out, so I asked the GCC team: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=123242

**Comment by brechtsanders** [comment]
Information so far from asking the GCC team:
- Eliminating duplicate strings in the linker is an ELF specific linker feature, this may not exist for COFF/PE linkers
- The compiler information is not in a loadable section, so it's not loaded from disk into memory
- The compiler option `-fno-ident` will leave out the compiler version in the compiled object file

@zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a Can you try your test again with the `-fno-ident` compiler flag?

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
1. i have no clue what that means.
2. PE section flags in gcc.exe and every executable gcc.exe produces are loaded in memory, no section is discarded. (all 8 sections loaded)
3. does not remove gcc version string duplicates, probably they meant to be used when compiling gcc itself.

**Comment by brechtsanders** [comment]
1. The linux binaries do support deduplication of strings by the linker. For Windows this probably doesn't exist (yet).
2. Apparently they assume it's not loaded because its needed, but probably Microsoft ignored that and loads it anyway.
3. I checked using `grep -c "built by Brecht Sanders"` and the one built with `-fno-ident` has 1 less. So yes, if I would be able to rebuild everything from scratch I might be able to reduce this even more. Unfortunatly my build recipes are not all ready for a global compiler flag.

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
>     2. Apparently they assume it's not loaded because its needed, but probably Microsoft ignored that and loads it anyway.

i did further inspection, it is not windows fault, the sections in PE are not marked as discardable.

**Comment by brechtsanders** [comment]
> i did further inspection, it is not windows fault, the sections in PE are not marked as discardable.

Feel free to join in on https://gcc.gnu.org/bugzilla/show_bug.cgi?id=123242

**Comment by zmn28hgbn59kcmlpio8unfh7fdre523esd28q9a** [comment]
i dont have time to further test and inspect, but:
> p.s. im happy with my old gcc 6.3 and current gcc 7.3 (also i have gcc 4.9.x around just in case for some other stuff)

i started to make my own crt, to use specifically with your gcc-7.5 distribution, so far so good, and executable size is so small and tiny.

and you can guess, it has only one instance of "GCC: (MinGW-W64 i686-posix-dwarf, built by Brecht Sanders) 7.5.0".
but this does not fully solve the duplication issue, every object NOT built with -fno-ident will contain a reference to gcc version string.

now consider this, my current state with my own crt:
one:
gcc -o crt.o -c crt.c
hello.c has simple hello world.
gcc -o hello.exe hello.c crt.o <...other compiler flags...> -lmsvcrt -s
hello.exe contains two duplicates of gcc version string.

two:
gcc -o crt.o -c crt.c **-fno-ident**
hello.c has simple hello world.
gcc -o hello.exe hello.c crt.o <...other compiler flags...> -lmsvcrt -s
hello.exe contains ONE gcc version string.

now this make things very clear, if you dont specify -fno-ident when you build your gcc package, then every single .o will contain a reference. (side note: the version string is put in .rdata which is a read only data section)
how many .a are there? each contain many .o, now you got the point why some stuff built with your distribution have huge amount gcc version string, the more they rely on included .o and .a in your package the more bloat is added to their final project executable.

by default (other distributions) only have one single gcc version string embedded in produced executables, you should really fix this before it is too late, searching winlibs online, seems winlibs is popular project, if people start to realize this issue im sure they will turn away.

not everybody have good or enough knowledge to make crt and handle exceptions or write assembly, or in 64-bit mode handle incorrect stack alignment, etc...

i believe i helped you alot, this should make winlibs better, if you ever in the future want to give me something then make sure it is:
gcc 7.5 that has one gcc version string, minimal package C and CPP compiler, dwarf for x86, seh for amd64, i like win32 threads because my exe will have 1 less dependency if i decide to use C threads, but i will accept posix threads but that means i will have to write my own threading library because i wont be using posix.

i hope you enjoy fixing your build scripts, good bye.

**Comment by brechtsanders** [comment]
Thanks a lot for convincing me. As I build all dependencies bottom up from scratch I should able to use the `-fno-ident` compiler flag for everything.

In fact I'm trying to build everything like that now. I wonder how much bloat that will remove. I hope there is a speed gain to, though that may be unnoticeable.

About the threads: I stick with pthreads builds because they offer best compatibility with sources coming from the Linux/Unix world. But please know that pthread (and the experimental mcfgthread) builds also include everything for your application to use win32 threads.

**Comment by eungenue** [comment]
Well, I didn't plan to respond again to this thread, but certainly the number of notifications I've got recently just made me )
Personally, I switched to https://github.com/niXman/mingw-builds-binaries/releases, which is from the official Mingw64 download page at https://www.mingw-w64.org/downloads/

I use it to compile to Windows XP SP3. So far so good. Hope this helps.
