### ISSUE TITLE
Requesting for GCC 12.1 release

### ISSUE THREAD

**Issue by cooky922** [brechtsanders/winlibs_mingw#102]
Maybe it's time for us to have a new GCC 12.1 compiler and also enable libbacktrace to support c++23 stacktrace library

**Comment by brechtsanders** [comment]
Working on it. First issue already reported: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105506

**Comment by brechtsanders** [comment]
UCRT not working yet, but MSVCRT is available here:
https://github.com/brechtsanders/winlibs_mingw/releases/tag/12.1.0-10.0.0-msvcrt-r1

I have build this with libbacktrace available on the build system.
Does that work for what you need, or are additional settings needed when building GCC?

**Comment by cooky922** [comment]
Maybe add `--enable-libstdcxx-backtrace=yes` to the configuration https://github.com/gcc-mirror/gcc/commit/3acb929cc0beb79e6f4005eb22ee88b45e1cbc1d

**Comment by brechtsanders** [comment]
The setting defaults to auto and my latest release was built with libbacktrace present.

Can you check if the features you need are present or missing?

**Comment by cooky922** [comment]
Unfortunately, I cannot see any of the libbacktrace headers and linker library in the release files.

**Comment by cooky922** [comment]
yes

**Comment by brechtsanders** [comment]
The goal of the winlibs standalone build tools package is to provide build tools.
Packages will be provided as separate packages in a next phase (see: https://github.com/brechtsanders/winlibs_recipes and https://github.com/brechtsanders/winlibs_tools/.)

Is you can see [here](https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/libbacktrace.winlib) libbacktrace can be easily built on Windows.

So since you will be including .h files it would make more sense to me consider this a separate package.

Do you have any arguments why libbacktrace should be distributed as part of the build tools and not as a library package?
