### ISSUE TITLE
Where to install sqlite3?

### ISSUE THREAD

**Issue by codenotworking** [brechtsanders/winlibs_mingw#104]
I'm a beginner at this, so please be patient.  I'm using Windows 10 and VS Code to write C code.  I have downloaded [WinLibs standalone build of GCC and MinGW-w64 for Windows](https://winlibs.com/) and added it to my PATH.  I can write C code and compile it with gcc.exe properly.

Now I am trying to add sqlite3 into winlibs.  I have downloaded the sqlite amalgamation and dll files from [sqlite.org](https://www.sqlite.org/download.html), which contain the following files:
```
Amalgamation.zip:
shell.c
sqlite3.c
sqlite3.h
sqlite3ext.h

Dll.zip
sqlite3.def
sqlite3.dll
```

I have placed `sqlite3.c` and `sqlite3.h` into `c:\dropbox\apps\mingw64\x86_64-w64-mingw32\include`.

Here is a simple C code I am trying to compile
```c
#include <stdio.h>
#include <sqlite3.h>

int main() {
    printf("%s", sqlite3_libversion());
    return 0;
}
```
Unfortunately when I attempt to compile, I receive an error.
```
C:\>gcc.exe "C:\Dropbox\Programming\c\c_testing\test5_1_sqlite.c" -o "c:\_program_output\c\test5_1_sqlite.exe" -Wall
c:/dropbox/apps/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\<MY_USERNAME>\AppData\Local\Temp\ccahCnOi.o:test5_1_sqlite:(.text+0xe): undefined reference to `sqlite3_libversion'
collect2.exe: error: ld returned 1 exit status
```
Do I have to put the `sqlite3.dll` somewhere within `mingw64`?
Would appreciate some help with properly installing sqlite3.

**Comment by brechtsanders** [comment]
You need to link against the library. You can probably do that by just adding the full path tp the DLL to the `gcc` command line.

The clean way is to have a `.dll.a` library file to link with, but gcc should be clever enough to know the ´.dll´ is a shared library.

I always recommend building all prerequisites with the exact same compiler for maximum stability (instead of linking with some downloaded package). But sqlite3 is very well-written so you can probably get away with this.

The way I build sqlite3 uses the MSYS2 shell and can be found [here](https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/sqlite3.winlib), but if you are a beginner that probably won't help you much.

**Comment by brechtsanders** [comment]
Note: for beginners' questions like this (which are not issues in the software provided here) it may be better to ask your question on forums like https://stackoverflow.com/

**Comment by codenotworking** [comment]
Okay, got it.  Thanks.
