### ISSUE TITLE
Some clarification on threads needed 

### ISSUE THREAD

**Issue by xtemp09** [brechtsanders/winlibs_mingw#133]
winlibs.com contains some information about UCRT and MSVCRT. Could you also provide some information about threads, since you released recently MCF?

I'm not sure if pthread-version of gcc 13 under Windows is needed anymore. If a user can use std::(j)thread pthreadslessly, perhaps, posix-threaded version will live only in archives. Though, I've never used win32 or MCF in production.

Are you planning on releasing henceforth MCF, posix-thread and win32 version or you will concentrate on one-two?

**Comment by brechtsanders** [comment]
The decision was made to go for native win32 thread builds, as this also includes pthreads availability and the aim is to be as native as possible.

MCF is fairly recent and there was a preliminary release to allow testing.

Since MCF takes advantage of native features of more recent Windows versions (Windows 7 and higher), it could be the way to go in the future if this offerce performance improvements.

However people also keep asking to support older Windows versions, so switching to MCF would be bad news for them.

When GCC 13 is finally released I may have another look at MCF.
