### ISSUE TITLE
Requesting win32 threading model

### ISSUE THREAD

**Issue by xtemp09** [brechtsanders/winlibs_mingw#149]
It has been discussed many times and I know that you are not planning on releasing gcc with win32 threading model.

Could you release it, at least, once with gcc 13.1 UCRT? I like the idea of usage of `std::thread` without additional libraries. I know that MCF changes something internally, but for me it just replacement of libwinpthread with just another library.

**Comment by brechtsanders** [comment]
The reason is that such build is missing POSIX threads (`pthread.h`), which is really needed to port a lot of sftware to Windows.
And it's practically very hard to maintain a mix of so many different release, so choices were made.
For GCC 13 MCF was just a first test, and there are issues, so I'm working on a POSIX thread build now too.
