### ISSUE TITLE
Difference between 9.3.0-7.0.0 and 9.3.0-7.0.0-r2

### ISSUE THREAD

**Issue by weizheng-chen** [brechtsanders/winlibs_mingw#15]
I want to use 9.3.0 toolchain, and there are 2 releases: 9.3.0-7.0.0 and 9.3.0-7.0.0-r2. 

What is different between them?

Which is better?
 
Thanks.

**Comment by brechtsanders** [comment]
Always use the latest one if possible.
I am constantly trying to improve things in the way the build is done.
Between those versions specifically I made sure ncurses was used everywhere instead of mixing ncurses and pdcurses in the different dependancies. This relates to console output (like color support) and didn't realle impact the compiler itself.
