### ISSUE TITLE
LLVM compiler-rt, libc++, libunwind and more

### ISSUE THREAD

**Issue by rsp4jack** [brechtsanders/winlibs_mingw#155]
Thanks for your awesome builds!

But, include more LLVM tools please! (like [mstorsjo/llvm-mingw](https://github.com/mstorsjo/llvm-mingw))

**Comment by brechtsanders** [comment]
The winlibs builds started out as GCC builds.

On request LLVM was added, but using the GCC standard libraries.

Because of this not all tools can be built.

It's probably better to use LLVM with its own standard libraries.

This is what https://github.com/mstorsjo/llvm-mingw provides. Is there a reason you don't use that build?

**Comment by rsp4jack** [comment]
Well, I thought I needed a build that provides a full GCC&MinGW64 and full LLVM toolkit. Now I find that it is better to use llvm-mingw (no wrappers) and winlibs (no LLVM) together.

**Comment by brechtsanders** [comment]
Yes, I do prefer LLVM without the wrappers too.

Plan is - if I find the time - to maybe one day make a seperate winlibs LLVM build without GCC or GCC's standard libraries.
