### ISSUE TITLE
My personal opinions and constructive criticism

### ISSUE THREAD

**Issue by 636C6F776E** [brechtsanders/winlibs_mingw#181]
Hello, I was looking for a suitable upgrade from TDM-GCC-64 9.2.0 and I came across WinLibs 9.5.0 and I'd like to touch on a few things:

1. WinLibs has too many extra programs -- GCC, GDB and Binutils are all that's needed, IMO
   - NASM? CMake? Doxygen? I will install them myself, separately, straight from upstream
   - Ninja? Never head of it and I don't want it
2. The extra programs are sometimes missing/not working?
   - WinLibs 9.5.0 x86_64 POSIX SEH MSVCRT: NASM is supposed to be included but it's missing
   - WinLibs 10.5.0 x86_64 POSIX SEH MSVCRT: Doxygen crashes with:
   > The procedure entry point `_ZSt28__throw_bad_array_new_lengthv` could not be located in the dynamic link library libstdc++-6.dll.
   - IMO preventing such issues in future releases constitutes a good argument for getting rid of the extra programs altogether and unbloating WinLibs, if simply trusting the user's judgement to manage them as independent installs wasn't a good enough argument already
3. This final point is a "me problem" but hopefully may still help you improve WinLibs: I'm using Windows 7 and I don't want to upgrade to a newer version, ever. I still happily use Windows XP on another machine but I'm too afraid to connect it to the Internet. :)

Anyway my "me problem" is that WinLibs uses Python 3.9 which is known to **not** run on Windows 7 -- Python 3.8 is the last version for Win7. Even though in your builds _python.exe_ seems to work just fine for me, I don't feel I can trust it to keep working without surprises. So my suggestion is simply: could you please specify the minimum requirements for each WinLibs release? Specifically which versions of Windows it will run on, and which versions of Windows it can target.

Finally, thank you for making the WinLibs distro and I hope I didn't come across as overly critical and/or unreasonable.

**Comment by Alcaro** [comment]
Personally I'm quite pleased that mingw32-make is present.

And if I want make, someone will want cmake, and someone else will want doxygen. It's hard to determine where the line should be drawn.

I agree that stating minimum versions would be an improvement. (And I agree that Windows >= 8 are smelly, I upgraded from 7 to Linux.)

**Comment by 636C6F776E** [comment]
> Personally I'm quite pleased that mingw32-make is present.

I did not mean to imply that GNU Make is an extra program: I too am pleased that it's included.

> And if I want make, someone will want cmake, and someone else will want doxygen. It's hard to determine where the line should be drawn.

IMHO TDM-GCC managed to find the sweet spot: the answer to the question "what does Code::Blocks need?"
* compiler
* debugger
* binutils
* make

> I upgraded from 7 to Linux.

That will be my path as well, unless something changes drastically over at Microsoft.

**Comment by brechtsanders** [comment]
I just added additional tools along the way that I have seen more and more as tools used for building.
These include CMake and Ninja.

The idea is that any IDE should be able to use the winlibs builds, even if that IDE supports things like CMake, Ninja, Doxygen, ...

But I do understand people using it for building only, for example from a CI environment, may not need the extra bloat (they may not even need GDB).

I am mainly focusing on recent versions of GCC (currently GCC13 and upcoming GCC14) and supported Windows versions (please know that Microsoft Windows 7 and older are officially unsupported and generally a bad idea to still be used).

I have played with the idea of making a basic package, and than the other stuff as add-on packages, but that will involve some duplicate files (`.dll` files in particular), and will be hell to support if people overwrite files from different releases.

Also GCC and LLVM in the same package is not such a good idea, and I think I should split these into completely different build environments at some point.

The above splitting issues could be solved by some kind of interactive installer, but I really like the current "just unzip and use it right away" way of working.

**Comment by jdb130496** [comment]
@brechtsanders I also like your way of integrating everything into one zip. Fully supporting that. Request to continue on this path in future so that everything can be found at one place. This is perhaps the only build on windows as compared to others, that is so comprehensive. Haven't come across a similar one elsewhere - particularly for windows. Is there any plan to release any update to gcc 13.2 (And of course other tools packed with that) in near future, before upscaling to gcc 14? Thank you for all your efforts. I switched to winlibs recently and found it to be great.

**Comment by brechtsanders** [comment]
Thanks for your feedback.

Some people have been asking for an installer, but I also prefer the "just unzip and start using" approach.

I regularly create new builds, mostly when new versions become available.

Ususally this follows GCC releases (see: https://gcc.gnu.org/develop.html).
So if a new GCC is released and there are no complications the next https://winlibs.com/ release follows pretty soon after.

When other components have new versions (especially MinGW-w64 and binutils) I sometimes also start building a new release.

Current stable version is 13.2.0 ([link](https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.2.0posix-17.0.6-11.0.1-msvcrt-r4)), and since GCC14 entered final stage 4 of the development process I may attempt to build another snapshot version of that as soon as I find the time.

**Comment by jdb130496** [comment]
Thank you, for that release 4 link (On winlibs it is still showing release 3 - so didn't know about that - but wish instead of MSVCRT there was also an option for UCRT for that release). and also for detailed clarifications about gcc and other utilities releases. Will watch out for them from time to time. With best wishes and request for continue to do the good work.

**Comment by brechtsanders** [comment]
The release 4 was for MSVCRT, as that is the more widely compatible version.

Can you tell me why you prefer the UCRT version? (I'm just curious)

It may interest you I'm also working on a [package manager](https://github.com/brechtsanders/winlibs_tools).
I currently have about 3000 working [build recipes](https://github.com/brechtsanders/winlibs_recipes), but I need to figure out for each of them if the license allows binary distribution before I can release anything.
All this work is after-hours as I don't get enough donations to dedicate more time to this.

**Comment by jdb130496** [comment]
@brechtsanders 

Thank you for your extra efforts - after hours work - which very few will appreciate and understand.

Some clarifications about me as necessary: Frankly and to be honest, I am purely a user rather than a seasoned developer. Actually my domain is Accounts and know little about C / C++ programming but thanks to these recent advances in AI chatbots like bing Ai / Chatgpt (I am dependent on them for all my coding requirements). I follow up with them after the testing of the code given by them and then through these kinds of chat sessions, I achieve what I want to - compile successfully, exe files. I would have stopped at Python but as I could not compile rdrand library on Python on Windows, I decided to go to even lower level - C and AI gave me the code for that intel intrinsic function for generating CRNG. Being open source lover, I did not want to do it using proprietary IDE like visual studio which brought me to using mingw64 / Msys / Cygwin. I discovered by comparison that yours is the most comprehensive zip package which other Mingw64 options do not have like LLVM, Cmake, etc.

About UCRT: Since it is comparatively new development compared to MSVCRT and is more widely used (again to be honest I am not sure but UCRT will allow me porting to Linux easily which MSVCRT may not)  - I am on dual boot with Windows / Archlinux on my laptop (also Fedora running from external USB), I thought UCRT will be more Universal than MSVCRT. That's why I was anxious why Release 4 does not have UCRT option, as all your previous versions have both MSVCRT and UCRT.

Thank you for responding to my queries raised out of my ignorance.

Request to continue to do good work at your own convenient time - which will help us all - entire community here.

**Comment by brechtsanders** [comment]
Thanks for elaborating.

Glad to hear my build came out as the best option :-)

Please know that UCRT requires newer Windows versions than MSVCRT, so in fact MSVCRT is the one that can be more widely used.

As for cross-platform portability of code between other platforms there is not that much difference between UCRT and MSVCRT. If you ever decide to write cross-platform C and/or have your code built by GitHub Actions n the cloud on different platforms, I made a minimal example here: https://github.com/brechtsanders/ci-test/

I'm also glad to hear people still dare to take on an "old" language as C, as most newbies tend to prefer the more flashy newer languages.

**Comment by jdb130496** [comment]
Glad to hear that portability won't be affected due to different builds - MSVCRT and UCRT (for release 4) - My windows is of course latest (11) but I know that there are lots of people out there, still on Windows 7 and even XP - So you have compiled release 4 considering wide compatibility.

Just out of my curiosity, In powershell when I issued the command cmake - I got errors (screenshots attached). Some dlls are missing or some other reason? - or is integration of the other tools with gcc in Mingw64 is not seamless or complete? Can you please look into? Or have I made some errors? 
![cmake_error_2](https://github.com/brechtsanders/winlibs_mingw/assets/57437119/60fa0865-c166-4ee0-917e-5997ce38a36c)
![cmake_error](https://github.com/brechtsanders/winlibs_mingw/assets/57437119/f8f8e96c-3a13-444e-8997-2c504b1dc690)

**Comment by jdb130496** [comment]
Just to add to my above response - I am on your UCRT Release 3

**Comment by brechtsanders** [comment]
I prefer plain old Command Prompt, it's quicker and for building I usually don't need any PowerShell stuff.

Though for day-to-day use and porting I use MSYS2 shell.

Have you tried specifying the full path to `cmake.exe` ?
If that works it's because your system wasn't able to find the `.dll` dependencies.
You could try to add the `bin` location containing these files to the `PATH` environment variable, but I strongly recommend that you don't do this system-wide. It's better to create a script or batch file to set variables like this and then remain at the prompt so you can use it.

Also, why don't you use an IDE like Code::Blocks? See https://winlibs.com/#usage-codeblocks on how to set it up with my release.

**Comment by jdb130496** [comment]
Thank you for the detailed response. Thank you for bringing to my notice that it is still better to use good old cmd than powershell. Yes, agreed - Msys2 is still best option, even better than than cmd - It has all linux like flexibility of using ./configure which cmd or powershell does not have.

Update on my previous feedback: I just downloaded your Release 4 MSVCRT and ran same command cmake in powershell. The error has disappeared - I don't know but something changed in release 4.

With regards and best wishes for good day.

**Comment by brechtsanders** [comment]
I will get started on a release 4 build of UCRT. There was definitely something wrong with r3 with regards to dependencies.

**Comment by jdb130496** [comment]
@brechtsanders 

Great! beyond words to express my happiness! Thank you! I will give me my feedback on cmake here once the release 4 UCRT is out.

With regards and respects for the good work you are doing taking extra pains and efforts,

**Comment by brechtsanders** [comment]
Just released in case you still would like UCRT:
https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.2.0posix-17.0.6-11.0.1-ucrt-r4

**Comment by jdb130496** [comment]
Sorry for my late response. Just saw it, downloaded, tested. Happy to report that the cmake error as above has disappeared in new UCRT release 4.

Thank you for quick turnaround and responses to my requests.

I will be definitely watching out the new releases as they come out. I have saved your winlibs.com - download page link in my favorites.

After your recommendations, I started using Msys2 shell more than powershell or cmd. I have defined shortcut on my desktop like this: D:\Programs\Msys2\msys2_shell.cmd -use-full-path. The advantage being, I can use full windows path (in path variable, I have defined your release)  so that I do not have to use native mingw64 tool-chain package installed by way of pacman command in Msys2 shell. For certain libraries exclusive to C++ not in the default mingw64 package, I download the binaries from their respective sites and copy respective files to bin, include and lib folders under your mingw64 installation to make them fully operational. They work more or less as expected.

With regards and best wishes for the new year 2024.

**Comment by jdb130496** [comment]
@brechtsanders 

Just out of my curiosity - I have gone through your releases page here. All GCC 14 pre-releases are MSVCRT (optional to UCRT). Is that purely because it is compatible with previous Windows versions or is it because releasing UCRT involves more work?

Ofcourse, as you have mentioned before, the code will remain portable across OS and in my case - occasional / casual use of gcc for compilation on Windows - may not be an issue with MSVCRT releases.

Thank you for your responses to my previous questions.

**Comment by brechtsanders** [comment]
It's only a prerelease (not intended for production use) and I just don't have the time to build it in all flavors.
MSVCRT is just the most widely usable...

**Comment by jdb130496** [comment]
Thanks. I understand your constraints.

**Comment by jdb130496** [comment]
Thank you, @brechtsanders for the new release 5 (gcc 13.2+LLVM+CLANG - UCRT) with latest binutils and cmake. Works seamlessly for building in msys2 shell.
