### ISSUE TITLE
Failed Building Hello,world Using Clang

### ISSUE THREAD

**Issue by zxunge** [brechtsanders/winlibs_mingw#182]
Hello brechtsanders!
        I'm glad to know There is such a great tool set. I've used the gcc in your package before, and recently I want to use the clang. It is linked against gcc's standard library as far as I know, and now I try to compile a simplest Hello World program, but I get these errors:
main.cpp:1:No type named _Destroy in namespace std.
main.cpp:1:No type named _Construct in namespace std.

But I then used the official released Clang(targeted msvc), it can compile the file well.

**Comment by brechtsanders** [comment]
Which winlibs.com release did you use exactly?

Honestly, winlibs.com has focus mostly on GCC, but LLVM was added due to popular demand.
But I'm not so sure LLVM and GCC with the same standard library is ideal.

If you need LLVM on Windows I recommend to us it with it's own standard library, like the one from:
https://github.com/mstorsjo/llvm-mingw/releases

**Comment by zxunge** [comment]
Thank you for Your reply. I'm using the gcc 13.2.0 posix + llvm 17.0.6 + MinGW-w64 11.0.1 ucrt on Windows 7. I agree that llvm isn't well compatible with gcc's library, maybe I need to change one, like mstorsjo's. Thanks.
