### ISSUE TITLE
LLVM Compiler Infrastructure missing "/clang/17/lib/windows/libclang_rt.profile-x86_64.a" causes linker error

### ISSUE THREAD

**Issue by jackL999** [brechtsanders/winlibs_mingw#188]
When building a program with profiling I get the following error, 
[...] /clang/17/lib/windows/libclang_rt.profile-x86_64.a': No such file or directoryclang++: error: linker command failed with exit code 1 (use -v to see invocation)

I understand that this particular library is built using compiler-rt in LLVM_ENABLE_PROJECTS as discussed here 

https://compiler-rt.llvm.org/

Are there any plans to provide this library and the others included in that project?

**Comment by brechtsanders** [comment]
I notice you use LLVM/CLang v17 while the latest winlibs release with LLVM is v18.1.1

The focus of https://winlibs.com/ is mainly on GCC. The LLVM supplied uses the GCC standard libraries instead of the ones from LLVM, which is not optimal.

If you really need LLVM/Clang on Windows you may be better off using the build from https://github.com/mstorsjo/llvm-mingw

**Comment by brechtsanders** [comment]
Can you please try if this issue is resolved with the most recent release at: https://github.com/brechtsanders/winlibs_mingw/releases/tag/13.2.0posix-18.1.3-11.0.1-msvcrt-r7 ?
