### ISSUE TITLE
gcc 10.1.0 - in gdb debugger tool the backspace is not working

### ISSUE THREAD

**Issue by ZsoltKantor** [brechtsanders/winlibs_mingw#19]
Installed GCC 10.1.0 + MinGW-w64 7.0.0 (release 1), everything works fine besides a tiny thing.
If you enter GDB and write a wrong command (misspelled for instance), you can not delete it because the backspace key is not working.
What you can do is to press enter and let the wrong command be handled by GDB.
With the official versions of MinGW-w64 (gcc 7.3, gcc 8.1) backspace works in GDB.

P.S.
I also tested with your gcc 7.5.0 MinGW-W64 i686-posix-dwarf, the same backspace issue with that too.
As I saw you integrated the GDB v9.1 in older distributions also (e.g. 7.5.0), so this could be a GDB configuration issue while compiling it from source code?

**Comment by brechtsanders** [comment]
This is a known problem still under investigation, see issue #9.

**Comment by ZsoltKantor** [comment]
thank you

**Comment by ZsoltKantor** [comment]
the backspace issue can be color related.
MinGW-W64 usesd no color for GDB v8.1 release and there the backspace works. Other projects, like yours and another one has GDB v9.1, respectively v8.3 with colors, and the backspace is not working.

**Comment by brechtsanders** [comment]
I have been investigating in the area of the use of curses, but the problem is the same when built against both ncurses and pdcurses.
But (as explained in #9) I noticed that in a MinTTY console backspace works, while in a regular console window it doesn't.
So it's not completely broken, but we need to figure out what is missing when it is running in a regular console window.

**Comment by ADAM5048** [comment]
Please get it fixed asap. It is really annoying

**Comment by ADAM5048** [comment]
Oh thank god, I found a solution to it! Finally, after 7 hours of searching and diagnosing, I managed to fix the issue by replacing libreadline8.dll with another version. 

Drop the following atachment into the directory where gdb resides and you are good to go.
[libreadline8.zip](https://github.com/brechtsanders/winlibs_mingw/files/4943329/libreadline8.zip)

( It stumbled upon this page : https://packages.msys2.org/package/mingw-w64-x86_64-gdb and fixed the issue by just replacing the former libread8 with the new one )

**Comment by brechtsanders** [comment]
@ADAM5048 you were probably replacing libreadline with a simpler version that wasn't even using ncurses, which would get read of the symptom, but I don't consider the problem solved like this.

But I was able to resolve the problem by fixing ncurses, which is used by readline.

I had the issue when running the MSYS2 shell directly (e.g. in Console2 or ConsoleZ) instead of using the MSYS launcher, kin which case TERM=cygwin (instead of TERM=xterm).
The problem was also present when running `sqlite3` built in the same environment.
When I ran `TERM=unknown sqlite3` backspace was running normally.
So I patched ncurses like this:
```
patch -ulbf ncurses/win32con/win_driver.c << EOF
@@ -643,3 +643,3 @@
        }
-    } else if (tname != 0 && stricmp(tname, "unknown") == 0) {
+    } else if (tname != 0 && (stricmp(tname, "unknown") == 0 || stricmp(tname, "cygwin") == 0)) {
        code = TRUE;
EOF
```
and now it works for `sqlite3`.

But I already had it fixed for gdb by patching gdb like this:
```
patch -ulbf readline/readline/terminal.c << EOF
@@ -655,3 +655,3 @@

-#ifndef __MSDOS__
+#if !defined (__MSDOS__) && !defined (__MINGW32__)
   if (_rl_term_backspace)
EOF
```
