### ISSUE TITLE
Virus detected CC 14.1.0 (with POSIX threads) 

### ISSUE THREAD

**Issue by UsmanTariq2** [brechtsanders/winlibs_mingw#207]
Hello, first of all i love winlibs. Have been using the compilers for quite some time now for everything.

I wanted to try out gcc14 , but sadly the msvcrt ( not ucrt) my virus alerts go up.

CC 14.1.0 (with POSIX threads) + LLVM/Clang/LLD/LLDB 18.1.5
![image](https://github.com/brechtsanders/winlibs_mingw/assets/57227434/04ae43c8-d1ff-4e4d-8ac9-218a7a020b29)

Please take a look into this. Thanks alot

**Comment by Alcaro** [comment]
#199 is already looking at that

**Comment by brechtsanders** [comment]
Download the version without LLVM, as the virus detections are only triggered by parts of LLVM.

**Comment by UsmanTariq2** [comment]
I like the LLVM parts

**Comment by brechtsanders** [comment]
The LLVM build in https://winlibs.com/ builds is not ideal as it uses the GCC standard library.

I hope to one day make a proper LLVM with its own standard library, but that would mean it won't be interchangeable with GCC.

Unfortunately I lack the time (since I still have dayjob) and my focus is mostly on GCC.

In the meantime I can recommend the LLVM build from https://github.com/mstorsjo/llvm-mingw
