### ISSUE TITLE
ucrt or msvcrt?

### ISSUE THREAD

**Issue by longnguyen2004** [brechtsanders/winlibs_mingw#23]
What C runtime does this toolchain link with, the old msvcrt or the new ucrt? I'm looking for a toolchain that doesn't link with msvcrt to avoid relying on such an old C runtime.

**Comment by brechtsanders** [comment]
That is a question for those who created MinGW and MinGW-w64, because that is the runtime used.
But as far as I can tell it does depend on MSVCRT.
But MSVCRT is still part of new Windows versions, so that shouldn't really be an issue.

Also I believe it is possible to tell the compiler to not use the standard C library, but then you need to avoid all functions that need it, or provide alternatives. Check out this link for example: https://stackoverflow.com/questions/57528555/how-do-i-build-against-the-ucrt-with-mingw-w64

**Comment by longnguyen2004** [comment]
UCRT **is** a C library, it's just a different one from MSVCRT. I believe mingw-w64 has an option `--with-default-msvcrt=...` to select between MSVCRT, MSVCR* (the versioned library) and UCRT. With `--with-default-msvcrt=ucrt`, mingw-w64 will use UCRT as its C library instead of MSVCRT

**Comment by brechtsanders** [comment]
I have spent the last few days building a winlibs.com GCC/MinGW-w64 build against UCRT runtime.
https://github.com/brechtsanders/winlibs_mingw/releases/tag/11.2.0-9.0.0-ucrt-r1
