### ISSUE TITLE
How do i configure this for Ubuntu?

### ISSUE THREAD

**Issue by Zaid385** [brechtsanders/winlibs_mingw#234]

**Comment by brechtsanders** [comment]
The whole idea of https://winlibs.com/ is to have a build environment for Windows on Windows.

Since MinGW-w64 also exists for other platforms to build for Windows on those other platforms (cross compilation) you can usually just install it using your Linux flavor's package manager. In your case `apt-get install mingw-w64` should install it.
Then to build instead of just `gcc` use `i686-w64-mingw32-gcc-win32` to build for Intel/AMD 32-bit Windows or `x86_64-w64-mingw32-gcc-win32` to build for Intel/AMD 64-bit Windows. Hopefully soon there will also be `aarch64-w64-mingw32-gcc-win32` soon to support Windows on ARM.

**Comment by Alcaro** [comment]
If you really want to run WinLibs on Ubuntu, you can simply run it in Wine.

**Comment by brechtsanders** [comment]
Why would you ever want to do that when there is a native version for Ubuntu?

That doesn't make any sense.

I'm pretty sure the way you propose to do it will be a lot slower.
