### ISSUE TITLE
POSIX mentioned in triplet

### ISSUE THREAD

**Issue by michael-o** [brechtsanders/winlibs_mingw#27]
Invoking says:
```
C:\>"c:\mingw64\bin\gcc.exe" --version
gcc.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Note the `x86_64-posix-seh` triplet while the MinGW W32 distro says:
```
C:\>gcc --version
gcc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Note the `x86_64-win32-seh-rev0`.

I think it might confuse users, like me, that your distro contains `posix` while your philosophy page says pure Windows. If that is correct, please document it as such.

**Comment by brechtsanders** [comment]
The POSIX threads in MinGW-w64 are implemented in a pure Windows way.
The Win32 theads build din't come with all the POSIX compatibility required to build certain packages, so that's why it wasn't chosen.
Note that you can still program Win32 threads all you want in your applications when using this compiler.

**Comment by brechtsanders** [comment]
I added this decision to http://winlibs.com/philosophy.html
