### ISSUE TITLE
in cmake ninja generator, i have error. mingw makefiles generator no problem.

### ISSUE THREAD

**Issue by mumin16** [brechtsanders/winlibs_mingw#3]
ninja: error: FindFirstFileExA(c/:/mingw64/include/c++/10.0.1): The filename, directory name, or volume label syntax is incorrect.

**Comment by brechtsanders** [comment]
Looks like your ninja build file has a wrong path starting with `c/:/` instead of `c:/` or `/c/`
You should fix that, or if the ninja build file was generated, fix it in the generator.
I have seen behavior like this before with meson, which is hard to get working properly on Windows under MSYS2. Is that what you are using?

**Comment by brechtsanders** [comment]
not an issue for this project as it currently doesn't include ninja
