### ISSUE TITLE
Support for Windows/XP ?

### ISSUE THREAD

**Issue by kl1059** [brechtsanders/winlibs_mingw#53]
I tried your recent i686 build on XP and "InitializeConditionVariable" is not defined in kernel32.dll

what is your position on XP support?

**Comment by brechtsanders** [comment]
My position doesn't matter. I just build GCC and MinGW-w64.

Specifically for InitializeConditionVariable: the documentation mentions it requires Windows Vista or higher, see: https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-initializeconditionvariable

**Comment by luisdallos** [comment]
The issue described by the OP is due to the ZSTD dynamic library (located at `mingw32\bin\libzstd-1.dll` and `mingw32\libexec\gcc\i686-w64-mingw32\11.1.0\libzstd-1.dll`) being built as a multi-threaded library (this is the default build as specified [here](/facebook/zstd/tree/dev/lib#multithreading-support)) and the multi-thread support on native M$ Windows targets requires Windows Vista or newer (due to the use of `condition variables`, which are not supported in Windows XP). The possible alternatives are:

- Building the ZSTD dynamic library as a single-threaded library.
- Patching the ZSTD sources to allow multi-threading support on native M$ Windows targets through `winpthreads` library (which still supports Windows XP).

**Comment by brechtsanders** [comment]
@kl1059 Why are you using a 20-year old Windows-version to compile software?

Even Windows 7 is end of life/support by Microsoft.

Personally I don't see the benefit of sacrificing improvements on systems that are supported (like multithreading in the case of ZSTD) to support older operating systems.

**Comment by kl1059** [comment]
thanks for the clarification.  fortunately we can build our own gcc compiler that does not link to the facebook dll.  this is a third option for what to do and will work fine for me.

thanks for the binaries you've shared with us - i do experiment with yours on windows 7 systems.
