### ISSUE TITLE
Issues with PCH (GCH) and wxWidgets

### ISSUE THREAD

**Issue by MortenMacFly** [brechtsanders/winlibs_mingw#57]
I am using GCC 11.1.0 + LLVM/Clang/LLD/LLDB 12.0.0 + MinGW-w64 8.0.2 - release 1 (LATEST) on Win10 to compile a 64 bit application based on wxWidgets. When using PCH the compiler repeatable crashes making it unable to compile all units for the executable. Unfortunately, it also crashes when turning off PCH explicitly, just at another position.

This is a command line w/ PCH, for example:
x86_64-w64-mingw32-g++.exe -Wextra -Wall -pipe -DwxUSE_UNICODE -DwxUSE_WX_RESOURCES=0 -O2 -m64 -mthreads -Winvalid-pch -fno-keep-inline-dllexport -DUSE_PCH -DWX_PRECOMP -DWXUSINGDLL -D__WXMSW__ -D__GNUWIN32__ -DHAVE_W32API_H -DWINVER=0x0601 -D__USE_MINGW_ANSI_STDIO=1 -Wnon-virtual-dtor -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Wmain -Wextra -Wall -std=gnu++14 -DwxUSE_WX_RESOURCES=0 -iquote.objs_64 -I.objs_64 -I. -ID:\Devel\wxWidgets31_64\include -ID:\Devel\wxWidgets31_64\lib\gcc_dll\mswu -Iexchndl\win64\include -c configmanager.cpp -o .objs_64\configmanager.o

Here, the process just crashes and I see:
"Process terminated with status 1."

This is a command line w/o PCH, for example:
x86_64-w64-mingw32-g++.exe -Wextra -Wall -pipe -DwxUSE_UNICODE -DwxUSE_WX_RESOURCES=0 -O2 -m64 -mthreads -Winvalid-pch -fno-keep-inline-dllexport -DNOPCH -DWXUSINGDLL -D__WXMSW__ -D__GNUWIN32__ -DHAVE_W32API_H -DWINVER=0x0601 -D__USE_MINGW_ANSI_STDIO=1 -Wnon-virtual-dtor -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Wmain -Wextra -Wall -std=gnu++14 -DwxUSE_WX_RESOURCES=0 -iquote.objs_64_no_pch -I.objs_64_no_pch -I. -ID:\Devel\wxWidgets31_64\include -ID:\Devel\wxWidgets31_64\lib\gcc_dll\mswu -c wiz_begin.cpp -o .objs_64_no_pch\wizard\wiz_begin.o

Here, I see:
internal error in mingw32_gt_pch_use_address, at config/i386/host-mingw32.c:192: MapViewOfFileEx: "Es wurde versucht, auf eine unzulässige Adresse zuzugreifen." (Its German and means "tried to access an invalid address".)

Is this version of WinLibs know to work stable or should I better switch to another one? If yes, which one is know to work reliable? :-)

**Comment by brechtsanders** [comment]
I have seen PCH issues across all MinGW versions. I always avoid precompiled headers when building projects like wxWidgets and Qt.

Note that if you retry building wxWidgets without PCH you should really start from a totally clean rebuild (with no traces of a previous PCH build), or you can still get errors.

GCC 11.1 is stable, but some changes in it require some changes in certain software to build properly, see: https://gcc.gnu.org/gcc-11/porting_to.html
(see for example https://bugreports.qt.io/browse/QTBUG-93452 , https://github.com/praat/praat/issues/1739).
Also I haven't been able to get the GCC nVidia (nvptx) offload engine to build, which build fine up to GCC 10.3.

So for some purposes sticking with GCC 10.3 may be preferred.

Anyway, the precompiled header issues is something to be fixed in GCC. Unfortunately I haven't been able to pinpoint the exact problem(s) so I haven't reported any specific bugs to GCC myself.

As the focus of winlibs.com is mainly building Windows versions of GCC against MinGW-w64 (and all prerequisites) there is not much I can do to help here.

Can you let me know if a fresh build of wxWidgets without PCH (CMake flag `-DwxBUILD_PRECOMP:BOOL=OFF`) works for you?

**Comment by MortenMacFly** [comment]
Thank you fort the hint to GCC 10.3, I'll try that one. Lets see if it is more stable.

BTW: Unfortunately it doesn't matter if I use PCH or non-PCH for wxWidgets and the app. The crashes during compilation remain, for both cases. So basically I cannot compile most of my apps with GCC 11.1.0. I'll check from time-to-time if newer versions will work more reliable and report back here. The last truly reliable GCC version that works w/o issues on PCH files for me is TDM 8.1.0. :-( (And yes, I always to a deep clean and full re-build if I switch the compiler.)

I guess you can close the ticket, I believe there is not much you can do about it in that situation...

**Comment by brechtsanders** [comment]
Okay, I will close this ticket.

Note that my builds of wxWidgets seem stable, but I build every single dependancy from source with the same compiler.
This avoids introducing instabilities/crashes caused by differences between compilers (threading model, exception model, standard C/C++ library, ...).

**Comment by satyampathak223** [comment]
> 

GCC 10.1.0 builds from Winlibs appear to be working fine with PCH ( GCH ) without any hassle , to get PCHs working on latest build you have to disable Address Space Layout Randomization ( ASLR ) for your OS , in windows 10 it can be done by 
`Windows defender -> App and browser control -> Exploit protection settings` and then disable  **Randomize memory allocations (Bottom up ASLR )** _it should be turned on by default_ .
