### ISSUE TITLE
Request gcc-11.x binaries for Mingw-w64 7.x

### ISSUE THREAD

**Issue by johnoel** [brechtsanders/winlibs_mingw#71]
I have tried releases built with Mingw-w64 8.x and 9.x which results in segmentation error or has weird linker warnings.  
The release  https://github.com/brechtsanders/winlibs_mingw/releases/tag/10.2.1-snapshot20200912 built with version 7.x seems to work.  Is it possible to get a release with gcc-11.x binaries built with Mingw-w64 7.x?

**Comment by brechtsanders** [comment]
What are the errors you get exactly?

I'm currently building over 2000 sources with my latest releases, and the only issues I have so far are related to the stack protector.

One cause for crashes may be that wrong DLL files are being loaded because they exist elsewhere in the locations listed in the `PATH` environment variable.

**Comment by johnoel** [comment]
Yes, it is mainly stack errors occur when using thread_local.  It only happens when using binaries build from 8.x and 9.x and just works if using 7.x.  What DLL files are needed?  

If you can show me the procedure to build the compiler, maybe I can track it down.

**Comment by brechtsanders** [comment]
Please see my remarks about known issues on https://winlibs.com/ and the relate bug report I submitted here: https://sourceforge.net/p/mingw-w64/bugs/818/

**Comment by brechtsanders** [comment]
I'm not going to move 2 major versions of MinGW-w64 back in time, so I will be closing this ticket.

Note that your issues may also be cause by mixing libraries build against different compiler versions.
