### ISSUE TITLE
Half precision (_Float16) support for x86_64

### ISSUE THREAD

**Issue by CGIONE** [brechtsanders/winlibs_mingw#72]
Hello, Brecht!

Thank you for a working and portable compiler for win32, it is very good. I prefer gcc x64 version without  llvm, clang etc. 
I'm interesting in testing half precision float16 performance on intel cpus (FP16 instuctions).

As stated in docs: https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html
1. There is a builtin datatype _Float16
2. GCC supports float16 on x86 targets with SSE2
3. Cant declare _Float16, get error "not supported on this target", is there a requirement to enable this type?

4. Docs mention a compiler flag "-mavx512fp16", but I get error "unrecognized command-line option '-mavx512fp16'; did you mean '-mavx512bf16'?"

5. So if I dont understand how to enable _Float16 datatype, maybe you can point some tips.
If there is no support for any float16 in WinLibs, maybe you consider adding it.

Thank you.

**Comment by brechtsanders** [comment]
I just build the existing GCC release for Windows, I don't actually add features to it.
For that you need to contact the GCC development team (https://gcc.gnu.org/bugs/).

On https://gcc.gnu.org/onlinedocs/gcc/Half-Precision.html they mention the type `_Float16` exists on certain architectures (like ARM, which doesn't always have hardware floating point capabilities).

But I don't see why you would use 16-bit fixed point on 32 or 64-bit CPU that have hardware floating capabilities. There's nothing to be gained there.

If you really need fixed point I would recommend using _Float32 on 32-bit Windows and _Float64 on 64-bit Windows.

Or maybe do some tests to see if there as any speed gain at all using fixed point instead of floating point.
