### ISSUE TITLE
MinGW is missing the GMP library?

### ISSUE THREAD

**Issue by pjshelton** [brechtsanders/winlibs_mingw#95]
Trying to use the winlibs mingw64 compiler to compile odb-2.5.0-b.21.  (I have managed to use this compiler to compile the latest staged build2 build tool.)

odb-2.5.0 includes system.h which resolves to mingw64\lib\gcc\x86_64-w64-mings32\11.2.0\plugin\include\system.h
which includes gmp.h at line 698.  However, the system is then unable to find gmp.h

I am not sure how it resolved to that, as when I created a testfile.cpp that contained just the line ```#include <system.h>``` and 
ran ```g++ testfile.cpp``` it failed to find system.h.

I am really sorry for being so dense.

**Comment by brechtsanders** [comment]
Adding just `gmp.h` to the standalone build package wouldn't solve your issue, since further down the line you would also need to link with the GMP libraries.

This project provides the build tools, and GMP is not a part of that.
But it's perfectly possible to compile GMP with these build tools.

I am working on a separate project with build recipes (https://github.com/brechtsanders/winlibs_recipes) that can be used via the build/package manager I'm also working on (https://github.com/brechtsanders/winlibs_tools).

See https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/gmp.winlib for details how to build GMP as both static and shared (DLL) libraries.

**Comment by pjshelton** [comment]
Thank you.
